include:
  - actualbudget/docker-compose.yml
  - caddy/docker-compose.yml
  - immich/docker-compose.yml
  - media-stack/docker-compose.yml
  - miniflux/docker-compose.yml
  - paperless/docker-compose.yml
  - soju/docker-compose.yml
  - syncthing/docker-compose.yml
