services:
  soju:
    image: codeberg.org/emersion/soju:v0.10.1
    restart: always
    container_name: soju
    ports:
      - 6667:6667
    volumes:
      - ./config:/soju-config/:ro
      - ./data:/var/lib/soju/
